# What is Numpy?
- NumPy is the fundamental package for scientific computing in Python.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data.

- NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

- This behavior is called locality of reference in computer science.


# Why use Numpy?
- NumPy can be used to perform a wide variety of mathematical operations on arrays.
- NumPy stands for 'numerical Python', and builds on the early work of the Numeric and Numarray libraries with the goal to give fast numeric computation to Python.

In [49]:
#import NumPy Library
import numpy
arr = numpy.array([5,10,15,20,25])
print(arr)

[ 5 10 15 20 25]


In [2]:

import numpy as np
arr = np.array([5,10,15,20,25])
print(arr)

[ 5 10 15 20 25]


In [3]:

#checking version of numpy
print(np.__version__)

1.23.1


In [4]:
import numpy as np
arr = np.array((10,20,30,40,50))
print(arr)
print(type(arr))

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [5]:

import numpy as np
arr = np.array(11)
print(arr)
print(type(arr))

11
<class 'numpy.ndarray'>


In [6]:

import numpy as np
arr = np.array([10,20,30,40])
print(arr)

[10 20 30 40]


In [7]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [8]:
import numpy as np
arr = np.array([[[1,2,3,4],[5,6,7,8]],[[10,20,30,40],[60,70,80,90]]])
print(arr)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[10 20 30 40]
  [60 70 80 90]]]


In [9]:
# Check Number of Dimensions
import numpy as np

n1 = np.array(11)
n2 = np.array([10,20,30,40])
n3 = np.array([[1,2,3,4],[5,6,7,8]])
n4 = np.array([[[1,2,3,4],[5,6,7,8]],[[10,20,30,40],[60,70,80,90]]])

print("n1 is ",n1.ndim,"-D Array")
print("n2 is ",n2.ndim,"-D Array")
print("n3 is ",n3.ndim,"-D Array")
print("n4 is ",n4.ndim,"-D Array")

n1 is  0 -D Array
n2 is  1 -D Array
n3 is  2 -D Array
n4 is  3 -D Array


In [10]:

import numpy as np
n2 = np.array([10,20,30,40], ndmin=6)
print(n2)
print("Dimension of n2 is :", n2.ndim)

[[[[[[10 20 30 40]]]]]]
Dimension of n2 is : 6


In [51]:
#np.ones & np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [52]:
np.random.random((3,4))

array([[0.54674545, 0.90883888, 0.85624459, 0.53476704],
       [0.68829745, 0.01995884, 0.30388265, 0.54748114],
       [0.04096392, 0.37422776, 0.29993146, 0.67833663]])

# Arrange

In [53]:
np.arange(1,12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [54]:
a1 = np.arange(10)
a2 =  np.arange(12,dtype=float).reshape(3,4)
a3 =  np.arange(8).reshape(2,2,2)


In [55]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [57]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

# NumPy Array Indexing

Access Array Elements

Array indexing is the same as accessing an array element.
We can access an array element by referring to its index number.
The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc

In [11]:
import numpy as np
arr = np.array([10,11,22,33,44,55,66,7,8,9,1245,9999,896885])

#Get the first element from the  array
print(arr[0])

#Get the second element from the  array
print(arr[1])

#Get the last element from the  array
print(arr[-1])

#Get the 4th element & 6th element from the array and add them
print(arr[3] + arr[5])

10
11
896885
88


In [12]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr)
print("third element of first row :",arr[0,2])

print("third element of 2nd row :",arr[1,2])

print("4th element of first row & 2nd element of 2nd row and add them :",arr[0,3] + arr[1,1])

[[1 2 3 4]
 [5 6 7 8]]
third element of first row : 3
third element of 2nd row : 7
4th element of first row & 2nd element of 2nd row and add them : 10


In [13]:
import numpy as np
arr = np.array([[[1,2,3,4],[5,6,7,8]],[[10,20,30,40],[60,70,80,90]]])
print(arr)
print(arr[0,0,0])
print(arr[0,1,3])
print(arr[1,0,2])

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[10 20 30 40]
  [60 70 80 90]]]
1
8
30


#  NumPy Array Slicing

→Slicing arrays

Slicing in python means taking elements from one given index to another given index.
We pass slice instead of index like this: [start:end].
We can also define the step, like this: [start:end:step].
If we don't pass start its considered 0
If we don't pass end its considered length of array in that dimension
If we don't pass step its considered 1

In [14]:
#Slice elements from index 1 to index 3 from the following array:
import numpy as np
arr = np.array([10,11,22,33,44,55,66,7,8,9,12,45,99,89,68,85])
print(arr[1:3])
     

[11 22]


In [15]:
#Slice elements from index 6 to the end of the array:
import numpy as np
arr = np.array([10,11,22,33,44,55,66,7,8,9,12,45,99,89,68,85])

print(arr[6:])

[66  7  8  9 12 45 99 89 68 85]


In [16]:
#Slice elements from the beginning to index 8 (not included):
import numpy as np
arr = np.array([10,11,22,33,44,55,66,7,8,9,12,45,99,89,68,85])

print(arr[:8])

[10 11 22 33 44 55 66  7]


In [17]:
import numpy as np
arr = np.array([10,11,22,33,44,55,66,7,8,9,12,45,99,89,68,85])

print(arr[-6:-1])
print(arr[-13:-6])

[12 45 99 89 68]
[33 44 55 66  7  8  9]


In [18]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])

print(arr[0,1:3])
print(arr[0, 1:4])
print(arr[0, 2:8])

print(arr[1, 0:4])

[2 3]
[2 3 4]
[3 4]
[5 6 7 8]


In [19]:

import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])

print(arr[0:2 ,1])
print(arr[0:2, 3])

print(arr[0:2 , 1:3 ])

[2 6]
[4 8]
[[2 3]
 [6 7]]


In [20]:
#Step Slicing
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])

print(arr[1:6:2])
print(arr[1:8:3])
print(arr[::3])

[2 4 6]
[2 5 8]
[1 4 7]


# Checking the Data Type of an Array

In [21]:

import numpy as np
arr = np.array([1, 2, -3, 4])
print(arr.dtype)

int32


In [22]:
import numpy as np
arr = np.array(['YouTube','Simplifiedlearner','Google' , 'Apple'])
print(arr.dtype)

<U17


In [23]:
#converting data type

import numpy as np
arr = np.array([1.1,2.6,9.89,5.76])
print(arr.dtype)

n1 = arr.astype("i")
print("The new array is :", n1)
print(n1.dtype)

float64
The new array is : [1 2 9 5]
int32


# *► NumPy Array Copy vs View*

The Difference Between Copy and View : The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.
The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.
The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view

In [24]:
import numpy as np
arr = np.array([1,2,3,4,5,6])

n1 = arr.copy()

arr[2] = 50

n1[0] = 89

print("Original Data:", arr)
print("Copied Data:", n1)

Original Data: [ 1  2 50  4  5  6]
Copied Data: [89  2  3  4  5  6]


In [25]:
import numpy as np
arr = np.array([1,2,3,4,5,6])

n1 = arr.view()

arr[0] = 22
n1[-1] = 8

print("Original Data:", arr)
print("Viewed Data:", n1)

Original Data: [22  2  3  4  5  8]
Viewed Data: [22  2  3  4  5  8]


# Array Shape

In [26]:

import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr)

print("Dimension of array is :", arr.ndim)
print("Shape of this array is :", arr.shape)

[[1 2 3 4]
 [5 6 7 8]]
Dimension of array is : 2
Shape of this array is : (2, 4)


In [27]:
# Reshape : 1D to 2D
import numpy as np
arr = np.array([5,10,15,20,25,30,35,40,45,50,55,60])
print("Dimension of Original Array:",arr.ndim)

n1 = arr.reshape(3,4)

print("Original Array:", arr)
print("Reshaped Array:→")
print(n1)
print("Dimension of Reshaped Array:",n1.ndim)

Dimension of Original Array: 1
Original Array: [ 5 10 15 20 25 30 35 40 45 50 55 60]
Reshaped Array:→
[[ 5 10 15 20]
 [25 30 35 40]
 [45 50 55 60]]
Dimension of Reshaped Array: 2


In [28]:
# 1D to 3D

import numpy as np
arr = np.array([5,10,15,20,25,30,35,40,45,50,55,60])

n1 = arr.reshape(2,3,2)

print("Original Array:", arr)
print("Dimension of Original Array:",arr.ndim)

print("Reshaped Array:→")
print(n1)
print("Dimension of Reshaped Array:",n1.ndim)
     

Original Array: [ 5 10 15 20 25 30 35 40 45 50 55 60]
Dimension of Original Array: 1
Reshaped Array:→
[[[ 5 10]
  [15 20]
  [25 30]]

 [[35 40]
  [45 50]
  [55 60]]]
Dimension of Reshaped Array: 3


# NumPy Array Iterating

In [29]:
# Iterate 1-D array
import numpy as np
arr = np.array([5,10,15,20,25,30,35,40,45,50,55,60])

for x in arr:
  print(x)

5
10
15
20
25
30
35
40
45
50
55
60


In [30]:
#Iterate 2-D array

import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])

for x in arr:
  print(x)

[1 2 3 4]
[5 6 7 8]


In [31]:
# Iterate 2-D array in saclar manner
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6
7
8


In [32]:
#Iterate 3-D array
import numpy as np
arr = np.array([[[1,2,3,4],[5,6,7,8]],[[10,20,30,40],[60,70,80,90]]])

for x in arr:
  print(x)

[[1 2 3 4]
 [5 6 7 8]]
[[10 20 30 40]
 [60 70 80 90]]


In [33]:
# Iterate 3-D array in saclar manner
import numpy as np
arr = np.array([[[1,2,3,4],[5,6,7,8]],[[10,20,30,40],[60,70,80,90]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
10
20
30
40
60
70
80
90


In [ ]:
# 

In [34]:
import numpy as np
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr)

for x,y in np.ndenumerate(arr):
  print(x,y)

[[1 2 3 4]
 [5 6 7 8]]
(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


# NumPy Joining Array

In [35]:
#Join two arays
import numpy as np

n1 = np.array([5,10,15,20])
n2 = np.array([2,4,6,8])

arr = np.concatenate((n2,n1))
print(arr)

[ 2  4  6  8  5 10 15 20]


In [36]:
#Join two 2-D array
import numpy as np

n1 = np.array([[1,2],[3,4]])
n2 = np.array([[6,7],[8,9]])

arr = np.concatenate((n1,n2))

print(arr)

[[1 2]
 [3 4]
 [6 7]
 [8 9]]


In [37]:
#Join two 2-D arrays along rows (axis=1):
import numpy as np

n1 = np.array([[1,2],[3,4]])
n2 = np.array([[6,7],[8,9]])

arr = np.concatenate((n1,n2), axis=1)

print(arr)

[[1 2 6 7]
 [3 4 8 9]]


# Joining Arrays Using Stack Functions

In [38]:
import numpy as np

n1 = np.array([5,10,15,20])
n2 = np.array([2,4,6,8])

arr = np.stack((n1,n2), axis=1)

print(arr)

[[ 5  2]
 [10  4]
 [15  6]
 [20  8]]


In [39]:
#Stacking Along Rows →hstack
import numpy as np

n1 = np.array([5,10,15,20])
n2 = np.array([2,4,6,8])

arr = np.hstack((n1,n2))

print(arr)
     

[ 5 10 15 20  2  4  6  8]


In [40]:
#Stacking Along Columns → vstack
import numpy as np

n1 = np.array([5,10,15,20])
n2 = np.array([2,4,6,8])

arr = np.vstack((n1,n2))

print(arr)
     

[[ 5 10 15 20]
 [ 2  4  6  8]]


# NumPy Searching Arrays

In [41]:
import numpy as np
n1 = np.array([5,10,15,5,5,20,5,2])

arr = np.where(n1 == 5)
print(arr) #this will return index of all the 5

(array([0, 3, 4, 6], dtype=int64),)


In [42]:
import numpy as np

n1 = np.array([[1,2,1,5,1],[1,5,1,3,4]])

arr = np.where(n1 == 1)
print(arr) 

(array([0, 0, 0, 1, 1], dtype=int64), array([0, 2, 4, 0, 2], dtype=int64))


In [43]:
import numpy as np
n1 = np.array([5,10,15,5,24,20,5,2])

arr = np.where(n1%2 == 0)
print(arr) #returns index of all even number

(array([1, 4, 5, 7], dtype=int64),)


In [44]:
import numpy as np
arr = np.array([2, 5, 6, 7, 8, 9])

n1 = np.searchsorted(arr, 5)
print(n1)

1


In [45]:
#Find the indexes where the values 3, 5, and 7 should be inserted:
import numpy as np
arr = np.array([1,2,4,6,8,9])

n1 = np.searchsorted(arr,[3,5,7])
print(n1)

[2 3 4]


In [46]:
import numpy as np
n1 = np.array([1,3,8,0,6,77,-2])

print(np.sort(n1))

[-2  0  1  3  6  8 77]


In [47]:
import numpy as np
n1 = np.array(['cat','boss', 'dog', 'apple'])

print(np.sort(n1))

['apple' 'boss' 'cat' 'dog']


In [48]:
import numpy as np

arr = np.array([[3, 2, 14], [5, 0, 1]])

print(np.sort(arr))

[[ 2  3 14]
 [ 0  1  5]]
